CREATE TABLE plant (
  id INT AUTO_INCREMENT PRIMARY KEY,
  plant_name_EN VARCHAR(100) NOT NULL,
  plant_name_AR VARCHAR(100) NOT NULL,
  description_EN VARCHAR(255) NOT NULL DEFAULT 'no info',
  description_AR VARCHAR(255) NOT NULL DEFAULT 'لا يوجد معلومات',
  price DECIMAL(10, 2) NOT NULL,
  newest BOOLEAN NOT NULL DEFAULT 1,
  recommended BOOLEAN NOT NULL DEFAULT 1,
  pot_EN VARCHAR(50) NOT NULL,
  pot_AR VARCHAR(50) NOT NULL,
  quantity INT NOT NULL,
  water_EN VARCHAR(255) NOT NULL DEFAULT 'no info',
  water_AR VARCHAR(255) NOT NULL DEFAULT 'لا يوجد معلومات',
  light_EN VARCHAR(255) NOT NULL DEFAULT 'no info',
  light_AR VARCHAR(255) NOT NULL DEFAULT 'لا يوجد معلومات',
  temperatures_EN VARCHAR(255) NOT NULL DEFAULT 'no info',
  temperatures_AR VARCHAR(255) NOT NULL DEFAULT 'لا يوجد معلومات',
  easy_EN VARCHAR(255) NOT NULL DEFAULT 'no info',
  easy_AR VARCHAR(255) NOT NULL DEFAULT 'لا يوجد معلومات',
  part_sun_EN VARCHAR(255) NOT NULL DEFAULT 'no info',
  part_sun_AR VARCHAR(255) NOT NULL DEFAULT 'لا يوجد معلومات',
  medium_EN VARCHAR(255) NOT NULL DEFAULT 'no info',
  medium_AR VARCHAR(255) NOT NULL DEFAULT 'لا يوجد معلومات',
  subcategory_id INT,
  category_id INT NOT NULL,
  FOREIGN KEY (subcategory_id) REFERENCES subcategory(id) ON DELETE CASCADE,
  FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE,
);
